package com.example.museumapp.viewModel

import androidx.lifecycle.ViewModel
import com.example.museumapp.model.MuseumAppState
import com.example.museumapp.model.resources.Author
import com.example.museumapp.model.resources.Work
import javax.inject.Inject

class AuthorViewModel @Inject constructor(
): ViewModel(){
    var autor: Author = Author()
    init {
        autor= Author(name = "Agustín Esteve y Marqués", cover = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Augustin_Esteve_presumed_self_portrait.jpg/220px-Augustin_Esteve_presumed_self_portrait.jpg", type = "Escuela Española"
            , Place_Birth_and_Dead = "Valencia 1753-1820", biography = "Hijo del pintor de retablos Agustín Esteve Torralba y de María Marqués, desciende de una familia de artistas que se remonta al siglo XV. Su formación comenzó bajo la dirección de su padre y continuó con su ingreso, en 1768, en la Academia de Bellas Artes de San Carlos de Valencia. En 1770 se matriculó en la Academia de Bellas Artes de San Fernando de Madrid. En su formación influyeron fundamentalmente tres artistas: Francisco Bayeu, Mariano Salvador Maella y Anton Raphael Mengs, siendo este último el que causó más impacto en el joven artista. No obstante, en 1775 Esteve conoció al pintor que más le marcó profesionalmente: Francisco de Goya, de quien fue estrecho colaborador. Su estilo en los retratos debe mucho al de Goya, aunque con características personales e individuales que lo hacen fácilmente reconocible. Durante el último cuarto del siglo XVIII, Esteve fue uno de los retratistas más buscados por la aristocracia cortesana, únicamente superado en las cotizaciones por Goya, recibiendo encargos de las familias más importantes del momento, destacando su relación con la Casa de Osuna. En esos años comienza su actividad de miniaturista, muy valorada por Goya. Coincidiendo con el reinado de Carlos IV, Esteve realizó muchas de las copias de los modelos de los retratos reales creados por Goya para distintos encargos públicos, asimismo realizó varios dibujos para ser grabados y llevó a cabo diversos encargos de pintura religiosa. La etapa dorada del pintor culminó con el cambio de siglo al ser nombrado, en junio de 1800, pintor de cámara y académico de mérito de la de Bellas Artes de San Carlos. Sin embargo, debido a la crisis de principios del siglo XIX -Guerra de la Independencia, advenimiento de Fernando VII- y al cambio de gusto del nuevo monarca, el pintor quedó relegado a un segundo plano. Tras sufrir diferentes achaques, en 1819 el rey le concedió la jubilación y se retiró a su ciudad natal hasta su muerte. De los retratos que posee el Museo del Prado, cabe destacar el de la joven de trece años Joaquina de Alcántara Téllez-Girón, hija de los IX duques de Osuna y futura marquesa de Santa Cruz, y el del niño de diez años Mariano San Juan y Pinedo, futuro conde consorte de la Cimera. En ambos el artista consigue reflejar el candor infantil, pero su técnica, aunque muy precisa, no alcanza la brillantez del aragonés, resultando una pincelada más pesada y opaca (Aguilar Torres, I. en E.M.N.P., Madrid, 2006, tomo III, pp. 1015-1016)." )
    }
}